### ISSUE TITLE
[Rails 3] NoMethodError: undefined method `formatter' if not using TaggedLogger

### ISSUE THREAD

**Issue by bjeanes** [timberio/timber-ruby#97]
Because of `timber/overrides/active_support_3_tagged_logging.rb`, in a default Rails 3 logging setup, having the `timber` gem in the Gemfile causes the following boot failure:

```
NoMethodError: undefined method `formatter' for #<ActiveSupport::BufferedLogger:0x007f92c8b101b8>
/Users/bjeanes/Code/timber-ruby/lib/timber/overrides/active_support_3_tagged_logging.rb:83:in `new'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application/bootstrap.rb:41:in `rescue in block in <module:Bootstrap>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application/bootstrap.rb:25:in `block in <module:Bootstrap>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `instance_exec'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `each'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/bjeanes/Code/timber-test/config/environment.rb:5:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/bjeanes/.gem/ruby/2.2.6/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
/Users/bjeanes/.gem/ruby/2.2.6/gems/railties-3.2.22.5/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/Users/bjeanes/.gem/ruby/2.2.6/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:335:in `exec'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:20:in `dispatch'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/cli.rb:11:in `start'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/exe/bundle:32:in `block in <top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/bjeanes/.gem/ruby/2.2.6/gems/bundler-1.14.4/exe/bundle:24:in `<top (required)>'
/Users/bjeanes/.gem/ruby/2.2.6/bin/bundle:23:in `load'
/Users/bjeanes/.gem/ruby/2.2.6/bin/bundle:23:in `<main>'
```

This is because the default logger is `ActiveSupport::BufferedLogger` and the `timber install` command only changes this in `config/environments/production.rb`.

Ideally, installing `timber` and even forgetting to run `timber install` should not cause this kind of disruption.

Putting aside for a moment the fact that this may not be possible in a backwards-compatible way, but I wonder if `Timber::Logger` shouldn't be wrapping the existing Logger (`Rails.logger = Timber::Logger.new(Rails.logger)`) instead of monkey-patching TaggedLogger et al so that it confirms to the Timber interface. Of course, presumably there's a good reason for this (such as Rails making a hard assertion that `Rails.logger.class === ActiveSupport::TaggedLogger` or something... but just a thought.

**Comment by binarylogic** [comment]
Yeah, I thought updating `ActiveSupport::TaggedLogging` would be a win-win since we aren't changing the functionality and older versions get a better implementation since it resolves concurrency issues. I'm going to see if we can fix this to be backwards compatible or simply patch the existing `ActiveSupport::TaggedLogging` module.

If you're interested there are 2 reasons we patch `ActiveSupport::TaggedLogging`:

1. The original implementation (Rails 3.X) wrapped the `logger` object with it's own class. This, of course, redefined the original `logger` object public API. And deviations from the `::Logger` API would then be hidden. I assume this is why they changed their approach in >= 4.X.

2. The new approach extends the logger formatter and intercepts the message, prefixing it with the tags, and coercing any object passed into a `String`. This is problematic when the object being passed is a `Timber::Event` as it doesn't get the chance to serialize properly (since `to_s`) is called automatically. Moreover the `Timber::LogDevices::HTTP` device expects the raw objects for a variety of reasons. Either way, it's changing the original behavior of the user specified formatter, and ideally it should be transparent.

**Comment by binarylogic** [comment]
@bjeanes this was a long time coming, but this was resolved in https://github.com/timberio/timber-ruby/pull/178.  Version `2.5.0` will include this fix.
